name: GrowMyGreens
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: ""
url: http://dhanyacm.github.io/GrowMyGreens
include: ["_pages"]
permalink: /:title/
permalink: /404.html
